# Generated by Django 5.2.4 on 2025-07-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome (Inglês)'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_es',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome (Espanhol)'),
        ),
    ]
