# Generated by Django 5.2.4 on 2025-07-29 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_country_name_en_country_name_es'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='Nome de usuário')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Endereço IP')),
                ('success', models.BooleanField(default=False, verbose_name='Sucesso')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
            ],
            options={
                'verbose_name': 'Tentativa de Login',
                'verbose_name_plural': 'Tentativas de Login',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='account',
            name='trial_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiração do trial'),
        ),
        migrations.AlterField(
            model_name='account',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.plan', verbose_name='Plano'),
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL),
        ),
    ]
