# Generated by Django 5.2.4 on 2025-07-29 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_loginattempt_account_trial_expires_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='verification_expires',
            new_name='verification_expires_at',
        ),
    ]
