# Generated by Django 5.2.4 on 2025-07-30 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_trial',
            field=models.BooleanField(default=False, verbose_name='É plano trial'),
        ),
        migrations.AddField(
            model_name='plan',
            name='trial_days',
            field=models.IntegerField(default=15, verbose_name='Dias de trial'),
        ),
    ]
