# Generated by Django 5.2.4 on 2025-07-30 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_plan_is_trial_plan_trial_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('BRL', 'Real Brasileiro'), ('USD', 'Dólar Americano'), ('EUR', 'Euro')], max_length=3, verbose_name='Moeda')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='core.plan', verbose_name='Plano')),
            ],
            options={
                'verbose_name': 'Preço do Plano',
                'verbose_name_plural': 'Preços dos Planos',
                'unique_together': {('plan', 'currency')},
            },
        ),
    ]
