# Generated by Django 5.2.4 on 2025-07-30 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_planprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='trial_expires_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='trial_expires',
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Ativa'), ('cancelled', 'Cancelada'), ('expired', 'Expirada')], default='trial', max_length=20, verbose_name='Status')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Mensal'), ('yearly', 'Anual')], default='monthly', max_length=20, verbose_name='Ciclo de cobrança')),
                ('start_date', models.DateTimeField(verbose_name='Data de início')),
                ('end_date', models.DateTimeField(verbose_name='Data de fim')),
                ('next_billing_date', models.DateTimeField(blank=True, null=True, verbose_name='Próxima cobrança')),
                ('auto_renew', models.BooleanField(default=True, verbose_name='Renovação automática')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.plan', verbose_name='Plano')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
                'ordering': ['-created_at'],
            },
        ),
    ]
