# Generated by Django 5.2.4 on 2025-07-30 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_account_trial_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Descrição (Inglês)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='description_es',
            field=models.TextField(blank=True, verbose_name='Descrição (Espanhol)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome (Inglês)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='name_es',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome (Espanhol)'),
        ),
    ]
