# Generated by Django 5.2.4 on 2025-07-30 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_plan_description_en_plan_description_es_plan_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planprice',
            name='yearly_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Anual'),
        ),
        migrations.AlterField(
            model_name='planprice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Mensal'),
        ),
    ]
