# Generated by Django 5.2.4 on 2025-08-01 01:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_user_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_first_access',
            field=models.BooleanField(default=True, verbose_name='Primeiro acesso'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de nascimento'),
        ),
    ]
