# Generated by Django 5.2.4 on 2025-08-01 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_user_company_plan_max_companies_usercompany_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['name'], 'verbose_name': 'Plano', 'verbose_name_plural': 'Planos'},
        ),
        migrations.RemoveField(
            model_name='plan',
            name='price',
        ),
    ]
