# Generated by Django 5.2.4 on 2025-08-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_plan_price_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='grace_period_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fim do período de carência'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='last_notification_sent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última notificação enviada'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('trial', 'Trial'), ('active', 'Ativa'), ('grace_period', 'Período de Carência'), ('cancelled', 'Cancelada'), ('expired', 'Expirada')], default='trial', max_length=20, verbose_name='Status'),
        ),
    ]
