# Generated by Django 5.2.4 on 2025-08-04 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_subscription_grace_period_until_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='Documento'),
        ),
    ]
