# Generated by Django 5.2.4 on 2025-08-04 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_company_cnpj'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='date_of_birth',
            new_name='birth_date',
        ),
    ]
