# Generated by Django 5.2.5 on 2025-08-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_company_address_number_company_city_company_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='continent',
            field=models.CharField(blank=True, max_length=50, verbose_name='Continente'),
        ),
        migrations.AddField(
            model_name='country',
            name='region',
            field=models.CharField(blank=True, max_length=50, verbose_name='Região'),
        ),
    ]
