# Generated by Django 5.2.4 on 2025-08-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número'),
        ),
    ]
