# Generated by Django 5.2.4 on 2025-08-12 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_company_address_number_company_city_company_state_and_more'),
        ('customers', '0002_customer_address_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name'], 'verbose_name': 'customers.model.customer', 'verbose_name_plural': 'customers.model.customers'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, verbose_name='customers.model.address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='customers.model.address_number'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='customers.model.birth_date'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='customers.model.city'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='customers.model.company'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.country', verbose_name='customers.model.country'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='document_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='customers.model.document_number'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='customers.model.email'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='customers.model.is_active'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=200, verbose_name='customers.model.name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True, verbose_name='customers.model.notes'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='customers.model.phone'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='social_network',
            field=models.CharField(blank=True, max_length=100, verbose_name='customers.model.social_network'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(blank=True, max_length=100, verbose_name='customers.model.state'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='customers.model.zip_code'),
        ),
    ]
