# Generated by Django 5.2.4 on 2025-08-07 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_scale_alter_product_scale'),
        ('products', '0005_scale_only'),
    ]

    operations = [
    ]
