# Generated by Django

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_merge_0004_scale_alter_product_scale_0005_scale_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='scale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.scale', verbose_name='Escala'),
        ),
    ]
