# Generated by Django 5.2.4 on 2025-08-12 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_company_address_number_company_city_company_state_and_more'),
        ('products', '0008_category_created_at_category_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'products.category_verbose', 'verbose_name_plural': 'products.category_verbose_plural'},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['code'], 'verbose_name': 'products.currency_verbose', 'verbose_name_plural': 'products.currency_verbose_plural'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'products.product_verbose', 'verbose_name_plural': 'products.product_verbose_plural'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['order_index', 'created_at'], 'verbose_name': 'products.product_image_verbose', 'verbose_name_plural': 'products.product_image_verbose_plural'},
        ),
        migrations.AlterModelOptions(
            name='producttype',
            options={'ordering': ['name'], 'verbose_name': 'products.product_type_verbose', 'verbose_name_plural': 'products.product_type_verbose_plural'},
        ),
        migrations.AlterModelOptions(
            name='scale',
            options={'ordering': ['name'], 'verbose_name': 'products.scale_verbose', 'verbose_name_plural': 'products.scale_verbose_plural'},
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='products.created_at'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='common.description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='common.active'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='common.name'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(max_length=3, unique=True, verbose_name='products.currency_code'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=50, verbose_name='products.currency_name'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='symbol',
            field=models.CharField(max_length=5, verbose_name='products.currency_symbol'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category', verbose_name='products.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='products.company'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='products.cost_price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='products.created_at'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='products.created_by'),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.currency', verbose_name='products.currency'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='common.description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='dimension_unit',
            field=models.CharField(choices=[('mm', 'products.millimeters'), ('cm', 'products.centimeters'), ('in', 'products.inches')], default='cm', max_length=2, verbose_name='products.dimension_unit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='dimensions_x',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='products.dimensions_x'),
        ),
        migrations.AlterField(
            model_name='product',
            name='dimensions_y',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='products.dimensions_y'),
        ),
        migrations.AlterField(
            model_name='product',
            name='dimensions_z',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='products.dimensions_z'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='common.active'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='common.name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='print_time_estimate',
            field=models.CharField(blank=True, max_length=20, verbose_name='products.print_time_estimate'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.producttype', verbose_name='products.product_type'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='products.sale_price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='scale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.scale', verbose_name='products.scale'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='products.stock_quantity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='products.updated_at'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='products.weight'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_unit',
            field=models.CharField(choices=[('g', 'products.grams'), ('kg', 'products.kilograms')], default='g', max_length=2, verbose_name='products.weight_unit'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='products.created_at'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/images/', verbose_name='products.images'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='products.primary_image'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='order_index',
            field=models.PositiveIntegerField(default=0, verbose_name='products.order'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='products.product_verbose'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='products.created_at'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='description',
            field=models.TextField(blank=True, verbose_name='common.description'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='common.active'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='common.name'),
        ),
        migrations.AlterField(
            model_name='scale',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='products.created_at'),
        ),
        migrations.AlterField(
            model_name='scale',
            name='description',
            field=models.TextField(blank=True, verbose_name='common.description'),
        ),
        migrations.AlterField(
            model_name='scale',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='common.active'),
        ),
        migrations.AlterField(
            model_name='scale',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='common.name'),
        ),
    ]
